Спринт I: ветка Sprint 1/step 2
SergeiShabanov1989/react-burger pull request #1
Opened 2024-05-24 10:55 UTC by SergeiShabanov1989

2024-05-24 12:11 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Хорошая работа.

Приложение начинает обрастать функционалом и уже постепенно проглядывается картина готового продукта.

### **Вы молодец!**

- Декомпозиция файлов по директориям соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;
- Есть модальные окна;
- Данные получают с сервера;

### **Но есть несколько замечаний, которые нужно исправить:**

- Нужно очистить проект от лишних файлов, которые остались при инициализации create-react-app.

  - App.test.tsx

- В компоненте App-header нужно поправить иконки - <https://disk.yandex.com/i/7M5b-pm87x_dNg>, можно только у первой ссылки оставить).

- В директории `components` должен быть компонент App. Компонент `App`, он также должен быть в папке (как и другие компоненты). Как правило, это основной компонент в React, который выступает в качестве контейнера для всех остальных компонентов;

- <https://disk.yandex.com/i/5c6fXUKIj8xNyg> - Нужно поправить боковой скролл, у вас он возникает из-за того что `header_container` имеет `100vw`;

- Необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

  Пример как правильно:

  ```js
  data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
  ```

  Проверьте во всём проекте.

### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2024-05-24 12:11 UTC, ArslanMustafin commented on src/App.tsx
> +      }
**Надо исправить:**

Добавьте проверку ответа сервера - res.ok:

Например:

```js
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответит не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```js
const checkResponse = res => {
  return res.ok ? res.json() : res.json().then(err => Promise.reject(err));
};
```

`fetch(someUrl).then(checkResponse)`

<!--  -->

**Можно лучше:**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```js
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}
```

и разместить их в отдельном файле `utils/burger-api.js`, а не описывать запросы в самом компоненте

```jsx
// использование
getIngredients()
  .then(setState)
  .catch(...)
  .finally()
```

2024-05-24 12:11 UTC, ArslanMustafin commented on src/App.tsx
> +const URL = 'https://norma.nomoreparties.space/api/ingredients';
**Надо исправить:**

вынесите базовый адрес сервера `https://norma.nomoreparties.space/api` сервера в константу в отдельный файл, а адрес эндпоинта можно оставить в самой функции запроса `${BURGER_API_URL}/ingredients`

2024-05-24 12:11 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +    (ingredient) => ingredient.type === 'main' || 'sauce'
**Можно лучше:**

тут лучше фильтровать так: `ingredient.type !== 'bun'`

2024-05-24 12:11 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +  ),
**Надо исправить:**

Здесь и в `BurgerIngredients`

Необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

Пример как правильно:

```js
data: PropTypes.arrayOf(ingredientType.isRequired).isRequired;
```

2024-05-24 12:11 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +      image_large: PropTypes.string,
**Надо исправить:**

Здесь и в `BurgerIngredients`

Нужно всем полям указать `.isRequired`

2024-05-24 12:11 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +    })
**Надо исправить**

Здесь и в `BurgerIngredients`

во многих компонентах дублируется описание PropTypes ингредиента
Следует вынести его в отдельный файл (можно создать файл prop-types.js в папке utils) и переиспользовать описание пропсов ингредиента, а не дублировать

2024-05-24 12:11 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +          <Modal setIsOpenModal={setIsOpenModal}>
**Надо исправить:**

`ModalOverlay` - должен быть в компоненте `modal`.

можно такую структуру сделать: 

```js
<>
    <ModalOverlay onClose={,,,} />
    <div className="modal">...</div>
</>
```

2024-05-24 12:11 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
> +      {isChoseIngredient && isOpenModal && (
**Можно лучше:**

кажется тут немного перебор с условиями, достаточно просто `isOpenModal`

2024-05-24 12:11 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
> +            />
**Надо исправить:**

Здесь и далее.

у вас тут перебор с пропсами)
можно упростить, вы передаёте уже объект ингредиента поэтому `name, image, price` не нужно передавать. Также можно передать просто 1 функцию в качестве обработчика клика. 

```js
<IngredientsItems
  key={ingredient._id}
  ingredient={ingredient}
  onClick={handleClick}
/>
```

2024-05-24 12:11 UTC, ArslanMustafin commented on src/App.tsx
> +        <Main isIngredients={state.isIngredients} />
**Надо исправить:**

проверьте во всём проекте.

Нужно поправить названия переменных, обычно  если слова начинаются с `is`, то предполагается что в переменной лежит boolean значение. А тут просто массив ингредиентов - `ingredients`

2024-05-24 12:11 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
> +        </ModalOverlay>
**Надо исправить:**

`ModalOverlay` - должен быть в компоненте `modal`.

можно такую структуру сделать: 

```js
<>
    <ModalOverlay onClose={,,,} />
    <div className="modal">...</div>
</>
```

2024-05-24 12:11 UTC, ArslanMustafin commented on src/components/ingredient-details/ingredient-details.jsx
> +};
**Надо исправить:**

у вас неверно описаны пропсы, вы тут используете пропс `ingredient`, и должны описать его.

2024-05-24 12:11 UTC, ArslanMustafin commented on src/components/modal/modal.jsx
> +      if (e.keyCode === 27) {
**Надо исправить:**

вынесите магическое значение 27 в именованную константу `const ESC_KEYCODE = 27`

2024-05-24 12:11 UTC, ArslanMustafin commented on src/components/popup/popup.jsx
> +export const Popup = (props) => {
**Надо исправить:**

Вроде бы этот компонент не используется, поэтому лучше его удалить.

2024-05-25 12:50 UTC, SergeiShabanov1989 commented on src/components/burger-constructor/burger-constructor.jsx
> +    (ingredient) => ingredient.type === 'main' || 'sauce'
исправил

2024-05-25 15:46 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

### **Сделает код лучше:**

- В компоненте App-header нужно поправить иконки - <https://disk.yandex.com/i/7M5b-pm87x_dNg>, можно только у первой ссылки оставить).

2024-05-25 15:46 UTC, ArslanMustafin commented on src/components/app-header/app-header.jsx
> +              <div className={headerStyles.link}>
**Можно лучше:**

Здесь и далее.

тут всё было верно)) должна быть ссылка

2024-05-25 15:46 UTC, ArslanMustafin commented on src/components/utils/prop-types.js
> +})
**Можно лучше:**

тут нужно всем полям указать `isRequired`

2024-05-25 15:46 UTC, ArslanMustafin commented on src/index.css
> +}
**Можно лучше:**

А точно ли тут нужен везде `!important`?

2024-05-25 19:18 UTC, SergeiShabanov1989 commented on src/index.css
> +}
да, без !important у меня дефолтный скролл в браузере

2024-05-25 19:19 UTC, SergeiShabanov1989 commented on src/components/utils/prop-types.js
> +})
забыл:) сейчас исправлю

2024-05-25 19:35 UTC, merged